---
# check update and incremental update
kind: pipeline
type: docker
name: incremental_build
trigger:
  event:
  - cron
  cron:
  - check_updates

volumes:
- name: dockersock
  temp: {}

services:
- name: docker_engine
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: build_repo
  image: archlinux
  environment:
    TZ: Europe/Paris
    PGP_KEY:
      from_secret: PGP_KEY
    SSH_KEY:
      from_secret: SOURCEFORGE_SSH_KEY
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - bash ./repo_build.sh "incremental" "$${PGP_KEY}" "$${SSH_KEY}"

- name: commit_packages_update
  image: appleboy/drone-git-push
  settings:
    TZ: Europe/Paris
    ssh_key:
      from_secret: CI_SSH_KEY
    author_name: BotCI
    author_email: bot@ci
    branch: master
    remote: git@github.com:zaggash/archlinux-aur.git
    commit: false
    force: false

- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: TELEGRAM_TOKEN
    to:
      from_secret: TELEGRAM_GROUPID
    format: markdown
    message: >
      {{#success build.status}}
      ✅ Incremental Arch Repo build #{{build.number}} of `{{repo.name}}` succeeded.


      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```


      🌐 {{ build.link }}
      {{else}}
      ❌ Incremental Arch Repo build #{{build.number}} of `{{repo.name}}` failed.


      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```


      🌐 {{ build.link }}
      {{/success}}
  when:
    status:
    - success
    - failure

---
# Cron pipeline full rebuild.
kind: pipeline
type: docker
name: full_repo_build

trigger:
  event:
  - cron
  cron:
  - full_build

volumes:
- name: dockersock
  temp: {}

services:
- name: docker_engine
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: build_repo
  image: archlinux
  environment:
    TZ: Europe/Paris
    PGP_KEY:
      from_secret: PGP_KEY
    SSH_KEY:
      from_secret: SOURCEFORGE_SSH_KEY
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - bash ./repo_build.sh "full" "$${PGP_KEY}" "$${SSH_KEY}"

- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: TELEGRAM_TOKEN
    to:
      from_secret: TELEGRAM_GROUPID
    format: markdown
    message: >
      ❌ Full Repo build #{{build.number}} of `{{repo.name}}` failed.  

      🌐 {{ build.link }}
  when:
    status:
    - failure

